### ISSUE TITLE
Identifying synset for a given word

### ISSUE THREAD

**Issue by VirajSalaka** [chmeyer/jotl#1]
I could not find any available documentation regarding find synonyms for a given word.

**Comment by chmeyer** [comment]
Use org.dkpro.jotl.OpenThesaurus:getSynsetsByWord(final String word) for this. 

In https://github.com/dkpro/dkpro-jotl/blob/master/src/test/java/org/dkpro/jotl/OpenThesaurusTest.java, you can also view some examples of how the library can be used.
